CREATE TABLE LOGINS(
    ID_LOGIN SERIAL PRIMARY KEY,
    USUARIO VARCHAR(20) NOT NULL,
    CONTRASENIA VARCHAR(20) NOT NULL
);

CREATE TABLE PERSONAS(
	ID_PERSONA VARCHAR(20) NOT NULL PRIMARY KEY,
	NOMBRES VARCHAR(200) NOT NULL,
	APELLIDOS VARCHAR(200) NOT NULL,
	TIPO_DOCUMENTO VARCHAR(20) NOT NULL,
	GENERO VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(200) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	LOGIN_ID INTEGER NOT NULL,
	CONSTRAINT FK_LOGIN_ID FOREIGN KEY(LOGIN_ID) REFERENCES LOGINS(ID_LOGIN)
);


CREATE TABLE MEDICOS (
	ID_MEDICO SERIAL PRIMARY KEY,
	ESPECIALIDAD VARCHAR(200) NOT NULL,
	FECHA_INGRESO TIMESTAMP NOT NULL,
	PERSONA_ID VARCHAR(20) NOT NULL,
	CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(ID_PERSONA)
);


CREATE TABLE FAMILIARES(
	ID_FAMILIAR SERIAL PRIMARY KEY,
	PARENTESCO VARCHAR(20) NOT NULL,
	FECHA_REGISTRO TIMESTAMP NOT NULL,
	PERSONA_ID VARCHAR(20) NOT NULL,
	CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(ID_PERSONA)
);


CREATE TABLE PACIENTES(
    ID_PACIENTE SERIAL PRIMARY KEY,
    FECHA_INGRESO TIMESTAMP NOT NULL,
    PERSONA_ID VARCHAR(20) NOT NULL,
	MEDICO_ID INTEGER NOT NULL,
	FAMILIAR_ID INTEGER NOT NULL,
    CONSTRAINT FK_MEDICO_ID FOREIGN KEY(MEDICO_ID) REFERENCES MEDICOS(ID_MEDICO),
	CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(ID_PERSONA),
	CONSTRAINT FK_FAMILIAR_ID FOREIGN KEY(FAMILIAR_ID) REFERENCES FAMILIARES(ID_FAMILIAR)
);

CREATE TABLE HISTORIAS_CLINICAS(
	ID_HISTORIA_CLINICA SERIAL PRIMARY KEY,
	FECHA TIMESTAMP NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	ESTADO_GENERAL VARCHAR(20) NOT NULL,
	MEDICO_ID INTEGER NOT NULL,
	PACIENTE_ID INTEGER NOT NULL,
	CONSTRAINT FK_MEDICO_ID FOREIGN KEY(MEDICO_ID)REFERENCES MEDICOS(ID_MEDICO),
	CONSTRAINT FK_PACIENTE_ID FOREIGN KEY(PACIENTE_ID)REFERENCES PACIENTES(ID_PACIENTE)
);

CREATE TABLE SIGNOS_VITALES(
    ID_SIGNO_VITAL SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(70) NOT NULL,
	FECHA TIMESTAMP NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    VALOR_MIN VARCHAR(10) NOT NULL,
    VALOR_MAX VARCHAR(10) NOT NULL,
	HISTORIA_CLINICA_ID INTEGER NOT NULL,
	OXIMETRIA VARCHAR(20),
	FRECUENCIA_RESPIRATORIA VARCHAR(20),
	FRECUENCIA_CARDIACA VARCHAR(20),
	TEMPERATURA VARCHAR(20), 
	PRESION_ARTERIAL VARCHAR(20),
	GLICEMIA VARCHAR(20),
	CONSTRAINT FK_HISTORIA_CLINICA_ID FOREIGN KEY(HISTORIA_CLINICA_ID)REFERENCES HISTORIAS_CLINICAS(ID_HISTORIA_CLINICA)
);
