CREATE TABLE HISTORIAS_CLINICAS(
	ID_HISTORIA_CLINICA SERIAL PRIMARY KEY,
	FECHA TIMESTAMP NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(20) NOT NULL,
	ID_TRANSACCION INTEGER NOT NULL
);

CREATE TABLE PERSONAS(
	ID_PERSONA VARCHAR(20) NOT NULL PRIMARY KEY,
	NOMBRES VARCHAR(200) NOT NULL,
	APELLIDOS VARCHAR(200) NOT NULL,
	TIPO_DOCUMENTO VARCHAR(20) NOT NULL,
	GENERO VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(200) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	USUARIO VARCHAR(100) NOT NULL,
	CONTRASENIA VARCHAR(20) NOT NULL
);


CREATE TABLE MEDICOS (
	ID_MEDICO SERIAL PRIMARY KEY,
	ESPECIALIDAD VARCHAR(200) NOT NULL,
	FECHA_INGRESO TIMESTAMP NOT NULL,
	PERSONA_ID VARCHAR(20) NOT NULL,
	CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(ID_PERSONA)
);


CREATE TABLE FAMILIARES(
	ID_FAMILIAR SERIAL PRIMARY KEY,
	PARENTESCO VARCHAR(20) NOT NULL,
	FECHA_REGISTRO TIMESTAMP NOT NULL,
	PERSONA_ID VARCHAR(20) NOT NULL,
	CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(ID_PERSONA)
);

CREATE TABLE ENFERMEROS(
    ID_ENFERMERO SERIAL PRIMARY KEY,
    FECHA_INGRESO TIMESTAMP NOT NULL,
    PERSONA_ID VARCHAR(20) NOT NULL,
    CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(ID_PERSONA)
);

CREATE TABLE AUXILIARES(
    ID_AUXILIAR SERIAL PRIMARY KEY,
    FECHA_INGRESO TIMESTAMP NOT NULL,
    PERSONA_ID VARCHAR(20) NOT NULL,
    CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(ID_PERSONA)
);

CREATE TABLE PACIENTES(
    ID_PACIENTE SERIAL PRIMARY KEY,
    FECHA_INGRESO TIMESTAMP NOT NULL,
    PERSONA_ID VARCHAR(20) NOT NULL,
	MEDICO_ID INTEGER NOT NULL,
	ENFERMERO_ID INTEGER NOT NULL,
	FAMILIAR_ID INTEGER NOT NULL,
    CONSTRAINT FK_MEDICO_ID FOREIGN KEY(MEDICO_ID) REFERENCES MEDICOS(ID_MEDICO),
	CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID) REFERENCES PERSONAS(ID_PERSONA),
	CONSTRAINT FK_ENFERMERO_ID FOREIGN KEY(ENFERMERO_ID) REFERENCES ENFERMEROS(ID_ENFERMERO),
	CONSTRAINT FK_FAMILIAR_ID FOREIGN KEY(FAMILIAR_ID) REFERENCES FAMILIARES(ID_FAMILIAR)
);

CREATE TABLE DIAGNOSTICOS(
	ID_DIAGNOSTICO SERIAL PRIMARY KEY,
	FECHA TIMESTAMP NOT NULL,
	COMENTARIOS VARCHAR(20) NOT NULL,
	ESTADO_GENERAL VARCHAR(20) NOT NULL,
	MEDICO_ID INTEGER NOT NULL,
	PACIENTE_ID INTEGER NOT NULL,
	PERSONA_ID VARCHAR NOT NULL,
	CONSTRAINT FK_MEDICO_ID FOREIGN KEY(MEDICO_ID)REFERENCES MEDICOS(ID_MEDICO),
	CONSTRAINT FK_PACIENTE_ID FOREIGN KEY(PACIENTE_ID)REFERENCES PACIENTES(ID_PACIENTE),
	CONSTRAINT FK_PERSONA_ID FOREIGN KEY(PERSONA_ID)REFERENCES PERSONAS(ID_PERSONA)
);

CREATE TABLE SUGERENCIAS_DE_CUIDADO(
	ID_SUGERENCIA SERIAL PRIMARY KEY,
	FECHA TIMESTAMP NOT NULL,
	SUGERENCIA VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	MEDICO_ID INTEGER NOT NULL,
	PACIENTE_ID INTEGER NOT NULL,
	CONSTRAINT FK_MEDICO_ID FOREIGN KEY(MEDICO_ID)REFERENCES MEDICOS(ID_MEDICO),
	CONSTRAINT FK_PACIENTE_ID FOREIGN KEY(PACIENTE_ID)REFERENCES PACIENTES(ID_PACIENTE)
);

CREATE TABLE SIGNOS_VITALES(
    ID_SIGNO_VITAL SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(70) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    VALOR_MIN VARCHAR(10) NOT NULL,
    VALOR_MAX VARCHAR(10) NOT NULL
);

CREATE TABLE DETALLES_DIAGNOSTICOS(
	ID_DETALLE_DIAGNOSTICO SERIAL PRIMARY KEY,
	SIGNO_VITAL_ID INTEGER NOT NULL,
	DIAGNOSTICO_ID INTEGER NOT NULL,
	VALOR_SIGNO VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	CONSTRAINT FK_SIGNO_VITAL_ID FOREIGN KEY(SIGNO_VITAL_ID) REFERENCES SIGNOS_VITALES(ID_SIGNO_VITAL),
	CONSTRAINT FK_DIAGNOSTICO_ID FOREIGN KEY(DIAGNOSTICO_ID) REFERENCES DIAGNOSTICOS(ID_DIAGNOSTICO)
);
